apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy-deployment
  labels:
    service: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: abasiakara/reverseproxy:v1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
       
---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  selector:
    service: udagram-reverseproxy
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080